version: '3.1'
services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password

  nginx:
    image: nginx:1.15
    volumes:
      - ./web/build:/var/www/html/web
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api
    links:
      - api

  api:
    image: node:12
    volumes:
      - ./api:/usr/src/app
    command: npm start
    working_dir: /usr/src/app/
    restart: always
    depends_on:
      - mysql
    links:
      - mysql

  build:
    build: '.'
    volumes:
      - "$SSH_AUTH_SOCK:/ssh-agent"
      - "~/.gitconfig:/root/.gitconfig"
      - "~/.ssh/known_hosts:/root/.ssh/known_hosts"
      - "./web:/app/web"
      - "./api:/app/api"
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
      - NODE_ENV=development
    depends_on:
      - mysql
    links:
      - mysql

  myadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
      - mysql:db
    ports:
      - "8082:80"
